### ISSUE TITLE
[Issue]: build is not working due to devtoolset-7-gcc-gfortran

### ISSUE THREAD

**Issue by jdgh000** [ROCm/hipSPARSE#545]
### Problem Description

```
/install.sh -cd
Creating project build directory in: ./build
Installing cmake3 from distro package manager
Last metadata expiration check: 1:23:38 ago on Sun Nov 17 21:43:19 2024.
Package cmake-3.26.5-2.el9.x86_64 is already installed.
Dependencies resolved.
Nothing to do.
Complete!
Installing devtoolset-7-gcc-gfortran from distro package manager
Last metadata expiration check: 1:23:41 ago on Sun Nov 17 21:43:19 2024.
No match for argument: devtoolset-7-gcc-gfortran
Error: Unable to find a match: devtoolset-7-gcc-gfortran


sudo yum install devtoolset-7-gcc-gfortran
Last metadata expiration check: 1:24:29 ago on Sun 17 Nov 2024 09:43:19 PM PST.
No match for argument: devtoolset-7-gcc-gfortran
Error: Unable to find a match: devtoolset-7-gcc-gfortran

```

### Operating System

rhel9

### CPU

epyc

### GPU

mi210

### ROCm Version

ROCm 6.2.3

**Comment by ppanchad-amd** [comment]
Hi @jdgh000. Internal ticket has been created to investigate your issue. Thanks!

**Comment by schung-amd** [comment]
Hi @jdgh000, thanks for pointing this out. It looks like that install script has not been updated to support RHEL 9, although the install docs say it should be supported, and the script is trying to install requirements for CentOS 7 instead. As a quick workaround, you can try changing https://github.com/ROCm/hipSPARSE/blob/362bca4fd52b89c55e84378dffbdd57061e8da10/install.sh#L145 to `local client_dependencies_centos_7=( "gcc-gfortran" ) `. I'll check with the internal team to see if anything else needs to be updated here.

**Comment by schung-amd** [comment]
It looks like the dependencies should be the same as RHEL 8; as a quick workaround for now, you can change https://github.com/ROCm/hipSPARSE/blob/9e21155befa05bc476c95034b072a144df19be34/install.sh#L182 from `== 8`  to `== 9`.

**Comment by jdgh000** [comment]
Looks like install.sh i have in rocsparse is completely different, i can't find a place to fit in the L128 change. 
Will this change be made into future rocm release?
 git branch -r ; git log | head -1
  m/roc-6.2.x -> rocm-6.2.4
commit 2d0f575b93394e2ef407336bc09b0d65d6c58dc6

**Comment by jdgh000** [comment]
actually i found it in 6.2.4, so I think it can be closed.
